[typo fix]: fix typo for some comment and method name
megaease/easegress pull request #177
Opened 2021-08-09 08:09 UTC by jxd134

branch: main
target: fix typo

2021-08-09 08:10 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 177 Deploy Test Success

2021-08-09 08:19 UTC, benja-wu approved these changes
LGTM

2021-08-09 08:20 UTC, localvar commented on pkg/object/httpserver/httpserver.go
> +// Status is the wrapper of runtimes Status.
this one is not a typo.

2021-08-09 08:21 UTC, benja-wu commented
@jxd134 

Auto testing failed due to the 
``` bash
# github.com/megaease/easegress/pkg/common [github.com/megaease/easegress/pkg/common.test]
272
pkg/common/signal_unix_test.go:30:42: undefined: SingalUsr2
273
# github.com/megaease/easegress/pkg/cluster [github.com/megaease/easegress/pkg/cluster.test]
274
FAIL	github.com/megaease/easegress/pkg/cluster [build failed]
275
pkg/cluster/cluster_test.go:358:11: undefined: isDataEuqal
276
FAIL	github.com/megaease/easegress/pkg/common [build failed]
277
pkg/cluster/cluster_test.go:374:10: undefined: isDataEuqal
```
You can check it locally by running `make test`.

2021-08-09 08:22 UTC, jxd134 commented on pkg/object/httpserver/httpserver.go
> +// Status is the wrapper of runtimes Status.
yes, it's a mistake

2021-08-09 08:23 UTC, jxd134 commented
@benja-wu 
Yes, it's a mistake.
I will fix it.

2021-08-09 08:25 UTC, benja-wu requested changes
Test cases are also needed to be updated.

2021-08-10 02:29 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 177 Deploy Test Success

2021-08-10 02:30 UTC, closed without merging

2021-08-10 02:41 UTC, benja-wu commented
Hi @jxd134 
I think this PR is very helpful to improve the code quality of Easegress.
Can you tell us the reason why u closed this PR? Thx.

2021-08-10 02:43 UTC, jxd134 commented
@benja-wu 
The code quality is poor.
I will fix it and open a new puul request.

2021-08-10 02:49 UTC, benja-wu commented
> @benja-wu
> The code quality is poor.
> I will fix it and open a new puul request.

Roger that!