Support mock service in mesh
megaease/easegress pull request #246
Opened 2021-09-09 10:20 UTC by benja-wu

* Add mocking service supporting in MeshController.
* Refactor MeshController's work `run` implementation.

2021-09-09 10:21 UTC, megaeasex requested changes
[TASK:easegress-pr-test FAILED]megaease/easegress Pull Request 246 Deploy Test failed

2021-09-09 10:33 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 246 Deploy Test Success

2021-09-13 07:17 UTC, localvar commented on pkg/object/meshcontroller/worker/worker.go
> +	if runnAble := startUpRoutine(); !runnAble {
```suggestion
	if runnable := startUpRoutine(); !runnable {
```

2021-09-13 07:24 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 246 Deploy Test Success

2021-09-13 07:30 UTC, localvar approved these changes

2021-09-14 03:44 UTC, xxx7xxxx approved these changes

2021-09-14 03:45 UTC, merged