[doc] add readme in cn
megaease/easegress pull request #267
Opened 2021-09-17 09:38 UTC by benja-wu

2021-09-17 09:39 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 267 Deploy Test Success

2021-09-18 01:39 UTC, localvar commented on README.zh-CN.md
> +- **集成性：** 简单的接口使它很容易与其他系统集成，如Kubernetes Ingress、[EaseMesh](https://github.com/megaease/easemesh) 边车、工作流等。
```suggestion
## Easegress 简介

`Easegress`是一个云原生流量协调系统，旨在提供：

- **高可用性：** 内置Raft共识和选主算法，提供99.99%的可用性。
- **流量编排：** 支持多种流量过滤器，轻松编排流量处理流程（Pipeline）。
- **高性能：** 基础功能采用轻量级方法实现，性能优异。
- **可观察性：** 周期性报告多种统计数据，系统状态尽在掌握。
- **可扩展性：** 良好的 API 设计，不必知道底层细节，也能自己开发过滤器和控制器。
- **集成性：** 接口简单，易于与其他系统集成，如Kubernetes Ingress、[EaseMesh](https://github.com/megaease/easemesh) 边车、工作流等。
```

2021-09-18 01:46 UTC, jxd134 commented on README.zh-CN.md
> +		- 时间限制器：** 限制执行的时间。
```suggestion
		- **时间限制器：** 限制执行的时间。
```

2021-09-18 01:47 UTC, jxd134 commented on README.zh-CN.md
> +		- **IP过滤：** 限制对IP地址的访问。
```suggestion
		- **IP过滤：** 限制对IP地址/地址段的访问。
```

2021-09-18 01:48 UTC, jxd134 commented on README.zh-CN.md
> +		- 网格主控：** 是管理网格服务生命周期的控制平面。
```suggestion
		- ** 网格主控：** 是管理网格服务生命周期的控制平面。
```

2021-09-18 01:49 UTC, jxd134 commented on README.zh-CN.md
> +	- **适应性**：在处理链中适应请求和响应。
适用性，无法让人直观理解其作用。
是指httpTemplate吗？

2021-09-18 01:50 UTC, jxd134 commented on README.zh-CN.md
> +- [API Aggregator](./doc/cookbook/api_aggregator.md) - 将许多 API 聚集成一个 API。
```suggestion
- [API Aggregator](./doc/cookbook/api_aggregator.md) - 将业务关联 API  聚合为单个 API。
```

2021-09-18 01:52 UTC, jxd134 commented on README.zh-CN.md
> +- [Workflow](./doc/cookbook/workflow.md) - 一个为一些API制作工作流程的例子。
```suggestion
- [Workflow](./doc/cookbook/workflow.md) - 将若干 API 进行组合，定制为工作流。
```

2021-09-18 01:53 UTC, jxd134 commented on README.zh-CN.md
> +我们可以从[发布页](https://github.com/megaease/easegress/releases)下载二进制文件。例如，我们使用linux版本。
```suggestion
我们可以从[发布页](https://github.com/megaease/easegress/releases)下载二进制文件。  
例如，我们使用linux版本。
```

2021-09-18 01:55 UTC, localvar commented on README.zh-CN.md
> +	- **适应性**：在处理链中适应请求和响应。
Thanks for pointing this out, this is a draft version that was mostly translated from the English version by AI, we are rendering the words.

2021-09-18 01:57 UTC, jxd134 commented on README.zh-CN.md
> +我们可以运行`easegress-server`而不指定任何参数，它通过打开默认的2379、2380、2381端口启动自己。当然，我们可以在配置文件中改变它们，或者在`easegress-server --help`中解释清楚的命令参数。
```suggestion
我们可以运行`easegress-server`而不指定任何参数（服务默认依赖于2379、2380、2381端口）。  
> 我们可以在配置文件中更改默认端口，或者在命令行启动时指定相关参数（参数具体释义可通过执行`easegress-server --help`命令获取）。
```

2021-09-18 01:57 UTC, benja-wu commented on README.zh-CN.md
> +	- **适应性**：在处理链中适应请求和响应。
As @localvar had said, thanks for the correction.

2021-09-18 01:59 UTC, jxd134 commented on README.zh-CN.md
> +	- **适应性**：在处理链中适应请求和响应。
get it

2021-09-18 02:11 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 267 Deploy Test Success

2021-09-18 03:28 UTC, megaeasex requested changes
[TASK:easegress-pr-test FAILED]megaease/easegress Pull Request 267 Deploy Test failed

2021-09-18 03:29 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 267 Deploy Test Success

2021-09-18 05:54 UTC, haoel commented on README.zh-CN.md
> +- [Workflow](./doc/cookbook/workflow.md) - 将若干 API 进行组合，定制为工作流。
```suggestion
- [API 聚合](./doc/cookbook/api_aggregator.md) - 将多个 API 聚合为一个。
- [函数即服务 FaaS](./doc/cookbook/faas.md) - 支持 Knative FaaS 集成。
- [高并发秒杀](./doc/cookbook/flash_sale.md) - 如何使用 Easegress 进行高并发的秒杀活动。
- [负载均衡](./doc/cookbook/load_balancer.md) - 各种负载均衡策略。 
- [分布式调用链](./doc/cookbook/distributed_tracing.md) - 如何使用 Zipkin 进行 APM 追踪。
- [Kubernetes入口控制器](./doc/cookbook/k8s_ingress_controller.md) - 如何作为入口控制器与 Kubernetes 集成。
- [高性能](./doc/cookbook/performance.md) - 性能优化，压缩、缓存等。
- [管道编排](./doc/cookbook/pipeline.md) - 如何编排 HTTP 过滤器来处理请求和应答。
- [弹力和容错设计](./doc/cookbook/resilience.md) - 断路器、速率限制、重试、时间限制等（移植自[Java resilience4j](https://github.com/resilience4j/resilience4j)
- [安全](./doc/cookbook/security.md) - 如何通过标头、JWT、HMAC、OAuth2 等进行认证。
- [服务网关](./doc/cookbook/service_proxy.md) - 使用 Zookeeper、Eureka、Consul、Nacos 等进行服务注册。
- [WebAssembly](./doc/cookbook/wasm.md) - 使用 AssemblyScript 来扩展 Easegress。
- [工作流](./doc/cookbook/workflow.md) - 将若干 API 进行组合，定制为工作流。
```

2021-09-18 06:52 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 267 Deploy Test Success

2021-09-18 08:46 UTC, haoel commented on README.zh-CN.md
> +## 用户案例
```suggestion
## 相关用例
```

2021-09-18 08:54 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 267 Deploy Test Success

2021-09-22 10:58 UTC, xxx7xxxx approved these changes

2021-09-23 02:17 UTC, localvar approved these changes

2021-09-23 02:32 UTC, merged