refactor: move from io/ioutil to io and os packages
megaease/easegress pull request #346
Opened 2021-11-02 03:35 UTC by Juneezee

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

2021-11-02 03:37 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 346 Deploy Test Success

2021-11-02 03:40 UTC, megaeasex requested changes
[TASK:easegress-pr-test FAILED]megaease/easegress Pull Request 346 Deploy Test failed

2021-11-02 03:41 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 346 Deploy Test Success

2021-11-02 03:44 UTC, megaeasex approved these changes
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 346 Deploy Test Success

2021-11-02 04:10 UTC, localvar approved these changes

2021-11-02 04:10 UTC, localvar approved these changes

2021-11-03 02:45 UTC, haoel approved these changes
Thanks for this PR.

2021-11-03 02:46 UTC, merged