add health check for load balance servers
megaease/easegress pull request #857
Opened 2022-11-23 09:14 UTC by samanhappy

This PR introduces a health check mechanism for proxy servers which support configuring probe interval, path, timeout, fail and pass threhold.

2022-11-24 03:35 UTC, localvar requested changes
when service discovery is enabled, the server list changes from time to time, this case is not handled by this pr.

2022-11-24 03:35 UTC, localvar commented on pkg/filters/proxy/loadbalance.go
> +	go func(t *time.Ticker) {
this goroutine is leaked

2022-11-24 03:35 UTC, localvar commented on pkg/filters/proxy/server.go
> +	health         atomic.Value
is it necessary to use `atomic.Value`? it seems there are only one goroutine that accesses this field.

2022-11-25 01:43 UTC, localvar commented on doc/reference/filters.md
> +| timeout | int | Timeout seconds for health check, default is 3 | No |
please use duration format for `interval` and `timeout`

2022-11-25 01:43 UTC, localvar commented on pkg/filters/proxy/loadbalance.go
> +	go func(t *time.Ticker) {
the code change here haven't resolve the leak.

2022-11-25 01:43 UTC, localvar commented on pkg/filters/proxy/basepool.go
> +	}
the old instance should be closed after the new instance is ready.

2022-11-28 00:56 UTC, localvar commented on pkg/filters/proxy/basepool.go
> +	}
please use [SwapPointer](https://pkg.go.dev/sync/atomic#SwapPointer) to refactor L135-139.

2022-11-28 00:56 UTC, localvar commented on pkg/filters/proxy/loadbalance.go
> +		blb.done <- true
```suggestion
		close(blb.done)
```

2022-11-28 00:56 UTC, localvar commented on pkg/filters/proxy/loadbalance.go
> +	ticker         *time.Ticker
no need to be a field of this struct, make it a local variable is better.
```suggestion
```

2022-11-28 00:56 UTC, localvar commented on pkg/filters/proxy/loadbalance.go
> +	}()
```suggestion
	ticker := time.NewTicker(blb.probeInterval)
	blb.done = make(chan bool)
	go func() {
		for {
			select {
			case <-blb.done:
			        ticker.Stop()
				return
			case <-ticker.C:
				blb.probeServers()
			}
		}
	}()
```

2022-11-28 02:52 UTC, localvar approved these changes

2022-11-28 02:58 UTC, suchen-sci approved these changes

2022-11-28 02:58 UTC, merged